workflows:
  macos-build:
    name: Build macOS App with SAM3D
    environment:
      vars:
        PYTHON_VERSION: "3.9"
    instance_type: mac_mini_m1
    scripts:
      - name: Set up Python environment
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Verify checkpoints
        script: |
          source venv/bin/activate
          python verify_checkpoints.py --checkpoints-dir checkpoints
          
      - name: Test model loading
        script: |
          source venv/bin/activate
          python demo.py --checkpoints-dir checkpoints --test-only
          
      - name: Build macOS app
        script: |
          source venv/bin/activate
          python build_mac_app.py --checkpoints-dir checkpoints
          
    artifacts:
      - build/*.dmg
      - build/*.app
      
  windows-build:
    name: Build Windows App with SAM3D
    environment:
      vars:
        PYTHON_VERSION: "3.9"
    instance_type: windows
    scripts:
      - name: Set up Python environment
        script: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt
          
      - name: Verify checkpoints
        script: |
          venv\Scripts\activate
          python verify_checkpoints.py --checkpoints-dir checkpoints
          
      - name: Test model loading
        script: |
          venv\Scripts\activate
          python demo.py --checkpoints-dir checkpoints --test-only
          
      - name: Build Windows app
        script: |
          venv\Scripts\activate
          python build_windows_app.py --checkpoints-dir checkpoints
          
    artifacts:
      - build/*.exe
      - build/*.msi
