workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install dependencies
        script: |
          python3 --version
          pip3 install --upgrade pip
          
          # FIRST install PyTorch separately
          echo "Installing PyTorch first..."
          pip3 install torch torchvision
          
          # THEN install the rest from requirements
          echo "Installing other dependencies..."
          pip3 install -r requirements.inference.txt

      - name: Verify critical files
        script: |
          echo "=== File Check ==="
          ls -la
          [ -f "demo.py" ] && echo "✓ demo.py found" || (echo "✗ demo.py missing"; exit 1)
          [ -d "notebook" ] && echo "✓ notebook/ found" || echo "⚠ notebook/ missing"
          [ -f "checkpoints/hf/pipeline.yaml" ] && echo "✓ Checkpoint config found" || echo "⚠ Checkpoint config missing - demo will fail"

      - name: Run the demo
        script: |
          echo "=== Starting SAM 3D Demo ==="
          python3 demo.py
          
          if [ -f "splat.ply" ]; then
            echo "✅ DEMO SUCCESS: splat.ply created!"
            ls -lh splat.ply
          else
            echo "❌ DEMO FAILED: No splat.ply output"
            echo "Check above for Python errors"
            exit 1
          fi

    artifacts:
      - "splat.ply"
