workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install core dependencies
        script: |
          brew install python@3.10
          pip3.10 install torch torchvision numpy gradio seaborn
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.10 install -e .
          cd ..
          
      - name: Test without kaolin
        script: |
          echo "Testing if kaolin is actually required..."
          python3.10 -c "
import sys
sys.path.append('notebook')
try:
    # Try to import without kaolin
    from inference import Inference
    print('✅ Can import inference without kaolin')
    print('Note: kaolin may only be needed for certain operations')
except Exception as e:
    print(f'Import error: {e}')
    print('This confirms kaolin is required')
"
          
      - name: Try demo
        script: |
          export CUDA_HOME="/opt/homebrew"
          python3.10 demo.py 2>&1 | head -20 || echo "Demo failed"

    artifacts:
      - "**/*.log"
