workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          brew install cmake ninja wget
          
      - name: Setup Python 3.9
        script: |
          echo "Installing Python 3.9 for kaolin compatibility..."
          brew install python@3.9
          python3.9 --version
          pip3.9 install --upgrade pip setuptools wheel
          
      - name: Install PyTorch for Python 3.9
        script: |
          pip3.9 install torch==2.0.1 torchvision==0.15.2 numpy
          python3.9 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"
          
      - name: Install gsplat
        script: |
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.9 install -e .
          cd ..
          
      - name: Install kaolin from source
        script: |
          echo "Installing kaolin from GitHub source..."
          pip3.9 install "git+https://github.com/NVIDIAGameWorks/kaolin.git@v0.17.0"
          
      - name: Install remaining dependencies
        script: |
          pip3.9 install seaborn==0.13.2 gradio==5.49.0
          
      - name: Fix inference.py environment issue
        script: |
          echo "Fixing CUDA_HOME in inference.py..."
          cp notebook/inference.py notebook/inference.py.backup
          sed -i '' "s/os.environ\[\"CUDA_HOME\"\] = os.environ\[\"CONDA_PREFIX\"\]/os.environ\[\"CUDA_HOME\"\] = '\/opt\/homebrew'/" notebook/inference.py
          
      - name: Test imports
        script: |
          python3.9 -c "import sys; sys.path.append('notebook'); \
          try: \
            from inference import Inference, load_image, load_single_mask; \
            print('✅ inference.py imports successful'); \
            import kaolin; \
            print(f'✅ kaolin {kaolin.__version__} loaded'); \
            import torch; \
            print(f'✅ torch {torch.__version__} loaded'); \
            print('✓ All dependencies installed successfully!'); \
          except Exception as e: \
            print(f'❌ Import error: {e}'); \
            import traceback; \
            traceback.print_exc()"
          
      - name: Run the demo
        script: |
          echo "=== Running demo.py ==="
          export CUDA_HOME="/opt/homebrew"
          python3.9 demo.py || echo "Note: Demo expected to fail without checkpoints"

    artifacts:
      - "**/*.log"
