workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          brew install cmake ninja wget
          
      - name: Setup Python 3.10
        script: |
          echo "Installing Python 3.10..."
          brew install python@3.10
          python3.10 --version
          pip3.10 install --upgrade pip setuptools wheel
          
      - name: Install PyTorch
        script: |
          pip3.10 install torch torchvision numpy
          python3.10 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"
          
      - name: Install gsplat
        script: |
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.10 install -e .
          cd ..
          
      - name: Install other dependencies
        script: |
          pip3.10 install gradio seaborn
          
      - name: Fix inference.py
        script: |
          echo "Fixing CUDA_HOME..."
          if [ -f "notebook/inference.py" ]; then
            sed -i '' "s/os.environ\[\"CUDA_HOME\"\] = os.environ\[\"CONDA_PREFIX\"\]/os.environ\[\"CUDA_HOME\"\] = '\/opt\/homebrew'/" notebook/inference.py
          fi
          
      - name: Simple test
        script: |
          echo "=== Testing imports ==="
          python3.10 -c "import torch; print(f'PyTorch: {torch.__version__}')"
          python3.10 -c "import gradio; print(f'Gradio: {gradio.__version__}')"
          python3.10 -c "import seaborn; print('Seaborn: OK')"
          echo "Core dependencies installed"
          
      - name: Run demo
        script: |
          echo "=== Running demo ==="
          export CUDA_HOME="/opt/homebrew"
          python3.10 demo.py 2>&1 | head -30 || echo "Demo completed (with or without errors)"

    artifacts:
      - "**/*.log"
