workflows:
  sam3d-demo:
    name: SAM 3D Demo
    # Correct environment structure
    instance_type: mac_mini_m1  # or 'linux_x2' for Linux
    
    scripts:
      - name: Install dependencies
        script: |
          # Install Python and dependencies
          python3 --version
          pip3 install --upgrade pip
          pip3 install -r requirements.inference.txt

      - name: Verify critical files
        script: |
          echo "=== File Check ==="
          ls -la
          [ -f "demo.py" ] && echo "✓ demo.py found" || (echo "✗ demo.py missing"; exit 1)
          [ -d "notebook" ] && echo "✓ notebook/ found" || echo "⚠ notebook/ missing"

      - name: Run the demo
        script: |
          echo "=== Starting SAM 3D Demo ==="
          python3 demo.py
          
          if [ -f "splat.ply" ]; then
            echo "✅ DEMO SUCCESS: splat.ply created!"
            ls -lh splat.ply
          else
            echo "❌ DEMO FAILED: No splat.ply output"
            exit 1
          fi

    artifacts:
      - "splat.ply"
