workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          # Install build tools gsplat might need
          brew install cmake ninja
          
      - name: Install PyTorch FIRST
        script: |
          python3 --version
          pip3 install --upgrade pip
          pip3 install torch torchvision numpy
          python3 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"

      - name: Install gsplat manually
        script: |
          echo "Cloning and installing gsplat manually..."
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3 install -e .
          cd ..

      - name: Install remaining dependencies
        script: |
          echo "Installing other requirements..."
          # Remove gsplat from requirements file temporarily
          grep -v "gsplat" requirements.inference.txt > temp_reqs.txt
          pip3 install -r temp_reqs.txt
          pip3 install kaolin==0.17.0 seaborn==0.13.2 gradio==5.49.0

    # ... rest of the YAML remains the same
