workflows:
  sam3d-demo:
    name: SAM3D Demo
    instance_type: mac_mini_m1
    scripts:
      - name: List files
        script: |
          echo "=== Repository Contents ==="
          ls -la
          echo "=== Checkpoints ==="
          ls -la checkpoints/ || echo "No checkpoints"
      - name: Install deps
        script: |
          pip install torch numpy
      - name: Test app
        script: |
          python demo.py --checkpoints-dir checkpoints --test-only
    artifacts:
      - "*.txt"
