workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          brew install cmake ninja wget
          
      - name: Setup Python 3.10 with kaolin workaround
        script: |
          echo "Installing Python 3.10 (gradio requires 3.10+)..."
          brew install python@3.10
          python3.10 --version
          pip3.10 install --upgrade pip setuptools wheel
          
      - name: Install PyTorch
        script: |
          pip3.10 install torch torchvision numpy
          python3.10 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"
          
      - name: Install gsplat
        script: |
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.10 install -e .
          cd ..
          
      - name: Install kaolin with older version workaround
        script: |
          echo "Installing kaolin with compatibility fix..."
          # Install kaolin-metrics instead (newer package)
          pip3.10 install kaolin-metrics
          # OR install specific kaolin from source if needed
          # pip3.10 install "git+https://github.com/NVIDIAGameWorks/kaolin.git@v0.15.0"
          
      - name: Install gradio and other deps
        script: |
          echo "Installing gradio (requires Python 3.10+)..."
          pip3.10 install gradio
          pip3.10 install seaborn
          
      - name: Fix inference.py
        script: |
          echo "Fixing CUDA_HOME in inference.py..."
          if [ -f "notebook/inference.py" ]; then
            sed -i '' "s/os.environ\[\"CUDA_HOME\"\] = os.environ\[\"CONDA_PREFIX\"\]/os.environ\[\"CUDA_HOME\"\] = '\/opt\/homebrew'/" notebook/inference.py
          fi
          
      - name: Test environment
        script: |
          echo "=== Testing environment ==="
          python3.10 -c "
import sys
sys.path.append('notebook')
try:
    # Try to import inference (will fail without checkpoints)
    from inference import Inference, load_image, load_single_mask
    print('✅ inference.py imports work')
except ImportError as e:
    print(f'⚠ Inference import issue: {e}')
    
# Test core dependencies
try:
    import torch
    print(f'✅ torch {torch.__version__}')
except ImportError as e:
    print(f'❌ torch failed: {e}')
    
try:
    import kaolin
    print(f'✅ kaolin loaded')
except ImportError:
    try:
        import kaolin_metrics
        print('✅ kaolin-metrics loaded (alternative)')
    except ImportError as e:
        print(f'⚠ kaolin issue: {e}')
        
try:
    import gradio
    print(f'✅ gradio {gradio.__version__}')
except ImportError as e:
    print(f'❌ gradio failed: {e}')
    
print('\\n✓ Environment setup complete')
print('Note: Demo will fail without checkpoints in checkpoints/hf/')
"
          
      - name: Run demo attempt
        script: |
          echo "=== Attempting demo (will fail without checkpoints) ==="
          export CUDA_HOME="/opt/homebrew"
          python3.10 demo.py 2>&1 | head -50 || echo "Demo failed (expected without checkpoints)"

    artifacts:
      - "**/*.log"
