workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          brew install cmake ninja wget
          
      - name: Setup Python 3.10
        script: |
          brew install python@3.10
          python3.10 --version
          pip3.10 install --upgrade pip
          
      - name: Install PyTorch
        script: |
          pip3.10 install torch torchvision numpy
          python3.10 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"
          
      - name: Install gsplat
        script: |
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.10 install -e .
          cd ..
          
      - name: Install other dependencies
        script: |
          pip3.10 install kaolin==0.17.0 seaborn==0.13.2 gradio==5.49.0
          
      - name: Fix inference.py environment issue
        script: |
          echo "Fixing CONDA_PREFIX error in inference.py..."
          # Create a backup
          cp notebook/inference.py notebook/inference.py.backup
          
          # Fix the CUDA_HOME line
          sed -i '' "s/os.environ\[\"CUDA_HOME\"\] = os.environ\[\"CONDA_PREFIX\"\]/os.environ\[\"CUDA_HOME\"\] = '\/opt\/homebrew'/" notebook/inference.py
          
          echo "Updated inference.py:"
          grep -n "CUDA_HOME" notebook/inference.py
          
      - name: Run the demo
        script: |
          echo "=== Starting SAM 3D Demo ==="
          # Set CUDA_HOME for the build environment
          export CUDA_HOME="/opt/homebrew"
          python3.10 demo.py
          
          if [ -f "splat.ply" ]; then
            echo "✅ DEMO SUCCESS: splat.ply created!"
            ls -lh splat.ply
          else
            echo "❌ DEMO FAILED: No splat.ply output"
            echo "Check above for Python errors"
            exit 1
          fi

    artifacts:
      - "splat.ply"
