workflows:
  sam3d-demo:
    name: SAM 3D Demo
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install system dependencies
        script: |
          brew install cmake ninja wget
          
      - name: Setup Python 3.10
        script: |
          echo "Installing Python 3.10..."
          brew install python@3.10
          python3.10 --version
          pip3.10 install --upgrade pip setuptools wheel
          
      - name: Install PyTorch
        script: |
          pip3.10 install torch torchvision numpy
          python3.10 -c "import torch; print(f'✓ PyTorch {torch.__version__} ready')"
          
      - name: Install gsplat
        script: |
          git clone https://github.com/nerfstudio-project/gsplat.git
          cd gsplat
          git checkout 2323de5905d5e90e035f792fe65bad0fedd413e7
          pip3.10 install -e .
          cd ..
          
      - name: Install kaolin (try multiple methods)
        script: |
          echo "Trying to install kaolin..."
          # Method 1: Try pip install
          pip3.10 install kaolin || echo "Standard kaolin install failed"
          
          # Method 2: Try from source if needed
          if ! python3.10 -c "import kaolin" 2>/dev/null; then
            echo "Installing kaolin from source..."
            pip3.10 install "git+https://github.com/NVIDIAGameWorks/kaolin.git@v0.15.0"
          fi
          
          # Method 3: Check if it's available as kaolinlib
          if ! python3.10 -c "import kaolin" 2>/dev/null; then
            echo "Trying kaolinlib..."
            pip3.10 install kaolinlib || echo "kaolinlib also not available"
          fi
          
          # Final check
          python3.10 -c "import sys; sys.stdout.write('Kaolin check: '); \
            try: import kaolin; print('SUCCESS'); \
            except: print('FAILED (but continuing)')"
          
      - name: Install other dependencies
        script: |
          pip3.10 install gradio seaborn
          
      - name: Fix inference.py
        script: |
          echo "Fixing CUDA_HOME..."
          if [ -f "notebook/inference.py" ]; then
            sed -i '' "s/os.environ\[\"CUDA_HOME\"\] = os.environ\[\"CONDA_PREFIX\"\]/os.environ\[\"CUDA_HOME\"\] = '\/opt\/homebrew'/" notebook/inference.py
          fi
          
      - name: Test environment
        script: |
          python3.10 -c "import sys; sys.path.append('notebook'); \
          try: from inference import Inference; print('✅ inference.py imports work'); \
          except ImportError as e: print(f'⚠ Inference import: {e}'); \
          try: import torch; print(f'✅ torch {torch.__version__}'); \
          except ImportError as e: print(f'❌ torch: {e}'); \
          try: import kaolin; print('✅ kaolin loaded'); \
          except ImportError as e: print(f'⚠ kaolin: {e} (may not be critical)'); \
          try: import gradio; print(f'✅ gradio {gradio.__version__}'); \
          except ImportError as e: print(f'❌ gradio: {e}'); \
          print('\\n✓ Environment setup attempt complete');"
          
      - name: Run demo
        script: |
          echo "=== Running demo ==="
          export CUDA_HOME="/opt/homebrew"
          python3.10 demo.py || echo "Note: Demo expected to fail without checkpoints"

    artifacts:
      - "**/*.log"
